insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('20230815', 'IRBR3F', 476, 41.39, 19701.64, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL), 
('20230724', 'IRBR3F', 47, 44.81, 2106.07, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)


select * from OPER_MANUAL
where QUANTIDADE ='423'

delete from OPER_MANUAL
where QUANTIDADE ='423'

insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('19990101', 'IRBR3F', 1, 41.41, 0.01, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)

insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('19990102', 'IRBR3F', 1, 41.41, 22900, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)


delete from OPER_MANUAL
WHERE DATA_INICIO ='19990102'

insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('19990101', 'IRBR3F', 1, 41.41, 12752.15, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)

insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('20231004', 'KRSA3F', 500, 0.77, 385, 3, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)

SELECT * FROM OPER_MANUAL
where PAPEL ='KRSA3F'

delete from OPER_MANUAL
where PAPEL ='IRBR3F'
and DATA_INICIO ='19990102'


insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('19990101', 'IRBR3F', 1, 41.41, 0.01, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)
