WITH MinValues AS (
                        SELECT
                            PAPEL,
                            MIN(VALOR_MEDIO) AS MIN_VALOR_MEDIO
                        FROM OPERACOES  with(nolock)
                        WHERE STATUS_COMPRA <> 'F'
                            AND DEAL_VENDA IS NULL
                        GROUP BY PAPEL
                    )
                    SELECT
                        o.PAPEL,
                        o.VALOR_MEDIO,
                        mv.MIN_VALOR_MEDIO,
                        CONVERT(VARCHAR, CONVERT(DATE, STUFF(STUFF(o.DATA_INICIO, 5, 0, '-'), 8, 0, '-')), 103) AS DATA_VALOR_MINIMO
                    FROM OPERACOES o with(nolock)
                    INNER JOIN MinValues mv ON o.PAPEL = mv.PAPEL AND o.VALOR_MEDIO = mv.MIN_VALOR_MEDIO
                    WHERE o.STATUS_COMPRA <> 'F'
                        AND o.DEAL_VENDA IS NULL;
                        
                        
CREATE TABLE OPERA_OPCOES (
DATA_INICIO varchar(8),
PAPEL VARCHAR(255),
QUANTIDADE INT,
VALOR_MEDIO FLOAT,
STRIKE FLOAT,
T_PUTCALL VARCHAR(5),
STATUS_VENDA CHAR(1),
STATUS_COMPRA CHAR(1),
DATA_VENCIMENTO [varchar](8)
);

--drop table OPERA_OPCOES

/*

INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','VALEO770',100,2.7,74.82,'PUT','S','N','20240315')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','MGLUM225',400,0.28,2.25,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','AMBPB171',100,0.75,17.12,'CALL','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','MGLUA225',400,0.27,2.25,'CALL','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','BMGBN270',2000,0.06,2.7,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','VALEM741',200,0.44,70.32,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','VALEM756',100,0.35,71.82,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','PETRM358',100,0.26,34.27,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','BRKMM182',100,0.36,18.25,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','DXCOM780',300,0.11,7.62,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','SUZBM520',100,0.25,51.01,'PUT','S','N','20240119')
INSERT INTO OPERA_OPCOES(DATA_INICIO,PAPEL,QUANTIDADE,VALOR_MEDIO,STRIKE,T_PUTCALL,STATUS_VENDA,STATUS_COMPRA,DATA_VENCIMENTO) VALUES ('20231219','MGLUA220',100,0.19,2.2,'CALL','S','N','20240119')
*/

SELECT * FROM OPERA_OPCOES



