select  * from OPERACOES
WHERE PAPEL ='ROMI3F'

select * from EMPVINICIAL
where EMPRESAS = 'BMGB4F'

select * from EMPVINICIAL
where U_VALOR = 'S'

SELECT * FROM OPERACOES
where PAPEL  = 'BMGB4F'


SELECT * FROM OPERACOES
where STATUS_COMPRA ='F'
AND DATA_FIM ='20230809'

SELECT * FROM OPERACOES
where STATUS_COMPRA <>'F'
and PAPEL ='AMBP3F'


SELECT sum(TOTAL_GASTO) FROM OPERACOES
where STATUS_COMPRA <>'F'

select sum(TOTAL_RETORNO) as TOTAL_RETORNO,sum(TOTAL_GASTO) as TOTAL_GASTO, ROUND((sum(TOTAL_RETORNO)/sum(TOTAL_GASTO))*100,2) as PERCENTUAL_RETORNO from OPEHIST
where DATA_FIM between '20230901' and '20230931'

SELECT * from OPEHIST
where DATA_FIM between '20230901' and '20230931'

select * from OPEHIST
where DATA_FIM ='20230810'


select * from EMPVINICIAL
where EMPRESAS ='RANI3F'
/*
UPDATE EMPVINICIAL
  SET U_VALOR ='N'
  where EMPRESAS ='RANI3F'
*/


select SUBSTRING(DATA_INICIO, 7, 2)+'/'+SUBSTRING(DATA_INICIO, 5, 2)+'/'+SUBSTRING(DATA_INICIO, 1, 4) DATA_INICIO,
PAPEL, QUANTIDADE, VALOR_MEDIO from OPERACOES
where STATUS_COMPRA <>'F'
order by PAPEL, VALOR_MEDIO desc


select * from OPERACOES
where STATUS_COMPRA <>'F'
and PAPEL ='TASA4F'




select * from EMPVINICIAL
where U_VALOR = 'S'
/*
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('RAIZ4F','N','S',4.40)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('SUZB3F','N','S',55.95)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('PMAM3F','N','S',4.73)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('BRKM5F','N','S',25.22)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('KRSA3F','N','S',1.50)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('BMGB4F','N','S',2.48)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('ITSA4F','N','S',9.60)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('KEPL3F','N','S',11.00)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('RRRP3F','N','S',38.41)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('FLRY3F','N','S',15.80)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('IRBR3F','N','S',41.80)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('ABEV3F','N','S',14.50)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('USIM5F','N','S',8.46)
INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('PSSA3F','N','S',23.70)
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('TIMS3F','N','S',13.50)     
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('REDE3F','N','S',5.5)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('GOAU3F','N','S',11.5)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('CBAV3F','N','S',10.5)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('MELK3F','N','S',3.7)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('SLCE3F','N','S',41)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('LAND3F','N','S',27.8)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('WIZC3F','N','S',7.5)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('NEOE3F','N','S',16.5)  
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('COCE5F','N','S',50)  
            INSERT INTO OPERACOES (DATA_INICIO,PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, STATUS_VENDA, STATUS_COMPRA,RETCODE,DEAL)
            VALUES ('20230724', 'IRBR3F', 47, 44.81, 2106.07, 60, 'S', 'M',10009,'MANUAL')
                         
                         */
                         
 INSERT INTO EMPVINICIAL (EMPRESAS,  B_VALOR, U_VALOR, VALOR_INI) VALUES 
                         ('TIMS3F','N','S',13.50)                        

                         
                         
  SELECT * FROM OPERACOES
where PAPEL  = 'RANI3F'                       
AND STATUS_COMPRA ='F'
AND DATA_INICIO ='20230823'


SELECT * FROM EMPVINICIAL
WHERE EMPRESAS ='IRBR3F'



UPDATE EMPVINICIAL
  SET VALOR_INI =8.50
  WHERE EMPRESAS ='KEPL3F'




/*
DELETE FROM OPERACOES
where PAPEL  = 'RANI3F'                       
AND STATUS_COMPRA ='F'
AND DATA_INICIO ='20230823'
*/


select * from OPER_MANUAL
        
        
insert into OPER_MANUAL (DATA_INICIO, PAPEL, QUANTIDADE, VALOR_MEDIO, TOTAL_GASTO, PRECO_SAIDA, TOTAL_RETORNO, Preco_Atual, dif_p_lucro_R, STATUS_VENDA, STATUS_COMPRA, RETCODE, DEAL, DEAL_VENDA, DATA_FIM) VALUES
('20230815', 'IRBR3F', 423, 41.41, 17516.43, 60, NULL, NULL, NULL, 'S', 'M', 10009, 'MANUAL', NULL, NULL)