CREATE TABLE CAPITALMES (
    DATA_INI VARCHAR(8) PRIMARY KEY,
    VALOR_MES FLOAT,
    MES_EX VARCHAR(20),
    RES_EMER FLOAT
);

ALTER TABLE CAPITALMES
ADD TOTAL_RESERVA FLOAT;

ALTER TABLE CAPITALMES
ADD PERC_L_P FLOAT;

SELECT * FROM CAPITALMES
WHERE SUBSTRING(data, 1, 4) = YEAR(GETDATE());

DELETE FROM CAPITALMES

drop table CAPITALMES


SELECT * FROM CAPITALMES

--pegar valor no my profit fechamento dos de ordens no mês
update CAPITALMES
  set LUCRO_PREJUIZO =1830.72
WHERE DATA_INI ='20230701'



UPDATE CAPITALMES
        SET PERC_L_P = round((LUCRO_PREJUIZO/CAPITAL_USO)*100,2)
